var readline = require("readline-sync");
var a = readline.question("znachenie a: ");
var b = readline.question("znachenie b: ");
var c;
console.log("znachenie a: "+a+", znachenie b: "+b+" ! ");
console.log("oi... chto-to poshlo ne tak!");
c=a;
a=b;
b=c;
console.log("vi govorili, chto a: "+a+", i chto b: "+b+" ? ");
